#!/bin/bash
NAMES=( John Eric Jessica )
# write your code here
NUMBERS=(1 2 3)
STRINGS=("Hello" "World")
NumberOfNames=${#NAMES[@]}
second_name=${#NUMBERS[1]}

echo ${NUMBERS[@]}
echo ${STRINGS[@]}
echo ${NAMES[2]}

echo "The number of names listed in the NAMES array:" ${#NUMBERS[@]}. 
echo "The second name on the NAMES list is:" ${NAMES[1]}.
